batch_size: 500
n_epochs: 500
max_path_length: 500
discount: 0.99
hidden_sizes: (256, 256)
hidden_nonlinearity: 'ReLU'
policy_lr: 3e-4
qf_lr: 3e-4
min_buffer_size: 1e+4
target_update_tau: 5e-3
gradient_steps_per_itr: 500
epoch_cycles: 40
min_std: -20 # e^-20
max_std: 2 # e^2
use_automatic_entropy: true
n_steps: 3
buffer_size: 5e+4
min_buffer_size: 1e+4
buffer_batch_size: 256
