batch_size: 5000
n_epochs: 4000
max_path_length: 500
discount: 0.99
hidden_sizes: (128, 128)
min_std: 0.5 # e^-20
max_std: 1.5 # e^2
std_share_network: True
hidden_nonlinearity: 'tanh'
learning_rate: 5e-4
lr_clip_range: 0.2
gae_lambda: 0.95
ent_coef: 1e-3
vf_coef: 0.2
max_grad_norm: 5
k_epoch: 5 # optimization epoch
layer_normalization: False
entropy_method: 'max'
pg_loss: 'surrogate_clip'
max_epochs: 256
buffer_batch_size: 32
init_std: 1
use_trust_region: False
normalize_inputs: True
normalize_outputs: True
